// ============================================================
// CivilOS Structural — Export Engine
// Phase 12: PDF (jsPDF) · DOCX (docx.js) · Excel (SheetJS)
// ============================================================

import { ReportDocument, ReportContent, ReportSection } from './reportEngine'
import { BBSSheet } from '../bbs/bbsEngine'

// ── PDF Export (jsPDF — loaded dynamically) ──────────────────

export async function exportToPDF(doc: ReportDocument): Promise<void> {
  // Dynamic import to avoid SSR issues
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const PW = 210, PH = 297
  const ML = 20, MR = 20, MT = 25, MB = 20
  const TW = PW - ML - MR   // text width
  let y = MT

  // ── Fonts & helpers ─────────────────────────────────────────
  const setFont = (size: number, style: 'normal'|'bold' = 'normal') => {
    pdf.setFont('helvetica', style)
    pdf.setFontSize(size)
  }

  const checkPage = (needed = 10) => {
    if (y + needed > PH - MB) {
      pdf.addPage()
      y = MT
      drawPageHeader()
    }
  }

  const drawPageHeader = () => {
    pdf.setDrawColor(30, 45, 74)
    pdf.setLineWidth(0.3)
    pdf.line(ML, 15, PW - MR, 15)
    setFont(7)
    pdf.setTextColor(100, 116, 139)
    pdf.text(doc.projectMeta.name, ML, 12)
    pdf.text(doc.title, PW / 2, 12, { align: 'center' })
    pdf.text(`Page ${pdf.getCurrentPageInfo().pageNumber}`, PW - MR, 12, { align: 'right' })
  }

  const drawLine = (color = [30, 45, 74] as [number, number, number]) => {
    pdf.setDrawColor(...color)
    pdf.setLineWidth(0.3)
    pdf.line(ML, y, PW - MR, y)
    y += 4
  }

  // ── Cover page ───────────────────────────────────────────────
  // Top color bar
  pdf.setFillColor(15, 23, 42)
  pdf.rect(0, 0, PW, PH, 'F')
  pdf.setFillColor(239, 68, 68)
  pdf.rect(0, 0, 8, PH, 'F')

  // Title block
  pdf.setTextColor(241, 245, 249)
  setFont(22, 'bold')
  pdf.text('CivilOS', 25, 60)
  setFont(16, 'bold')
  pdf.setTextColor(239, 68, 68)
  pdf.text('STRUCTURAL', 25, 72)
  setFont(12)
  pdf.setTextColor(148, 163, 184)
  pdf.text(doc.title, 25, 85)

  // Divider
  pdf.setDrawColor(30, 45, 74)
  pdf.setLineWidth(0.5)
  pdf.line(25, 92, PW - 20, 92)

  // Project details
  pdf.setTextColor(226, 232, 240)
  const meta = doc.projectMeta
  const detailsY = 105
  const details = [
    ['Project:',  meta.name],
    ['No.:',      meta.projectNo],
    ['Client:',   meta.client || '—'],
    ['Engineer:', meta.engineer || '—'],
    ['Address:',  meta.address],
    ['Date:',     meta.date],
    ['Code:',     meta.code],
  ]
  details.forEach(([k, v], i) => {
    setFont(9, 'bold')
    pdf.setTextColor(100, 116, 139)
    pdf.text(k, 25, detailsY + i * 9)
    setFont(9)
    pdf.setTextColor(226, 232, 240)
    pdf.text(v, 60, detailsY + i * 9)
  })

  // Footer
  setFont(7)
  pdf.setTextColor(71, 85, 105)
  pdf.text('Generated by CivilOS Structural v2.0 — BNBC 2020 / ACI 318-19', PW / 2, PH - 15, { align: 'center' })
  pdf.text(new Date().toLocaleString(), PW / 2, PH - 10, { align: 'center' })

  // ── Content pages ────────────────────────────────────────────
  for (const section of doc.sections) {
    if (section.id === 'cover') continue  // already rendered

    pdf.addPage()
    y = MT
    drawPageHeader()
    y += 5

    for (const item of section.content) {
      checkPage(15)
      renderPDFContent(pdf, item, ML, MR, TW, y, (newY: number) => { y = newY }, checkPage, setFont)
    }
  }

  // Save
  const filename = `${doc.projectMeta.projectNo}-${doc.type}.pdf`
    .replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_.]/g, '')
  pdf.save(filename)
}

function renderPDFContent(
  pdf: any, item: ReportContent,
  ML: number, MR: number, TW: number,
  y: number, setY: (n: number) => void,
  checkPage: (n?: number) => void,
  setFont: (size: number, style?: 'normal'|'bold') => void
) {
  const PW = 210

  switch (item.type) {
    case 'heading': {
      const sizes: Record<number, number> = { 1: 13, 2: 11, 3: 10 }
      const sz = sizes[item.level] ?? 10
      checkPage(sz + 6)
      if (item.level === 1) {
        pdf.setFillColor(15, 23, 42)
        pdf.rect(ML, y - 4, TW, sz + 4, 'F')
        pdf.setTextColor(239, 68, 68)
      } else if (item.level === 2) {
        pdf.setDrawColor(30, 58, 95)
        pdf.setLineWidth(0.5)
        pdf.line(ML, y + sz - 1, PW - MR, y + sz - 1)
        pdf.setTextColor(226, 232, 240)
      } else {
        pdf.setTextColor(148, 163, 184)
      }
      setFont(sz, 'bold')
      pdf.text(item.text, ML, y + sz - 2)
      setY(y + sz + 5)
      break
    }

    case 'paragraph': {
      setFont(9)
      pdf.setTextColor(148, 163, 184)
      const lines = pdf.splitTextToSize(item.text, TW)
      checkPage(lines.length * 5 + 3)
      pdf.text(lines, ML, y)
      setY(y + lines.length * 5 + 3)
      break
    }

    case 'keyvalue': {
      checkPage(item.items.length * 6 + 4)
      item.items.forEach((kv, i) => {
        const rowY = y + i * 6
        if (i % 2 === 0) {
          pdf.setFillColor(13, 18, 33)
          pdf.rect(ML, rowY - 3, TW, 6, 'F')
        }
        setFont(8, 'bold')
        pdf.setTextColor(100, 116, 139)
        pdf.text(kv.key + ':', ML + 2, rowY + 1)
        setFont(8)
        pdf.setTextColor(226, 232, 240)
        pdf.text(`${kv.value}${kv.unit ? ' ' + kv.unit : ''}`, ML + 70, rowY + 1)
      })
      setY(y + item.items.length * 6 + 4)
      break
    }

    case 'table': {
      const colW = TW / item.headers.length
      checkPage(15)

      // Header row
      pdf.setFillColor(30, 45, 74)
      pdf.rect(ML, y - 4, TW, 8, 'F')
      setFont(8, 'bold')
      pdf.setTextColor(59, 130, 246)
      item.headers.forEach((h, i) => pdf.text(String(h), ML + i * colW + 2, y))
      setY(y + 6)

      // Data rows
      item.rows.forEach((row, ri) => {
        checkPage(7)
        if (ri % 2 === 0) {
          pdf.setFillColor(13, 18, 33)
          pdf.rect(ML, y - 3, TW, 6, 'F')
        }
        setFont(8)
        row.forEach((cell, ci) => {
          pdf.setTextColor(ci === 0 ? 226 : 148, ci === 0 ? 232 : 163, ci === 0 ? 240 : 184)
          pdf.text(String(cell), ML + ci * colW + 2, y + 1)
        })
        setY(y + 6)
      })
      setY(y + 4)
      break
    }

    case 'checklist': {
      item.items.forEach(ci => {
        checkPage(7)
        const colors: Record<string, [number, number, number]> = {
          pass: [34, 197, 94], fail: [239, 68, 68],
          warning: [249, 115, 22], not_checked: [71, 85, 105],
        }
        const col = colors[ci.status] ?? [71, 85, 105]
        pdf.setFillColor(...col)
        pdf.rect(ML, y - 2, 2, 5, 'F')
        setFont(8, ci.status === 'fail' ? 'bold' : 'normal')
        pdf.setTextColor(...col)
        pdf.text(ci.status.toUpperCase().padEnd(12), ML + 4, y + 2)
        pdf.setTextColor(148, 163, 184)
        pdf.text(ci.label, ML + 30, y + 2)
        pdf.setTextColor(226, 232, 240)
        pdf.text(ci.value, PW - MR - 30, y + 2)
        setY(y + 6)
      })
      setY(y + 3)
      break
    }

    case 'formula': {
      checkPage(14)
      pdf.setFillColor(10, 15, 30)
      pdf.rect(ML, y - 3, TW, 12, 'F')
      pdf.setDrawColor(30, 58, 95)
      pdf.rect(ML, y - 3, TW, 12)
      setFont(9, 'bold')
      pdf.setTextColor(96, 165, 250)
      pdf.text(item.latex, ML + 4, y + 3)
      setFont(8)
      pdf.setTextColor(100, 116, 139)
      pdf.text(item.description, ML + 4, y + 9)
      setY(y + 14)
      break
    }

    case 'spacer':    setY(y + 6); break
    case 'pagebreak': pdf.addPage(); setY(25); break
  }
}

// ── Excel / CSV Export (SheetJS) ──────────────────────────────

export async function exportBBSToExcel(sheet: BBSSheet): Promise<void> {
  const XLSX = await import('xlsx')

  const wb = XLSX.utils.book_new()

  // ── Sheet 1: Summary ─────────────────────────────────────────
  const summaryData = [
    ['BAR BENDING SCHEDULE — SUMMARY'],
    ['Project:', sheet.projectName, '', 'No.:', sheet.projectNo],
    ['Engineer:', sheet.preparedBy, '', 'Date:', sheet.date],
    [],
    ['Bar ⌀ (mm)', 'No. of Bars', 'Total Length (m)', 'Weight (kg)', '% of Total'],
    ...sheet.summary.map(s => [
      `⌀${s.dia}`,
      s.totalBars,
      s.totalLength.toFixed(1),
      s.totalWeight.toFixed(1),
      sheet.grandTotal.weight > 0
        ? `${(s.totalWeight / sheet.grandTotal.weight * 100).toFixed(1)}%`
        : '0%',
    ]),
    [],
    ['GRAND TOTAL', sheet.grandTotal.bars, '', sheet.grandTotal.weight.toFixed(1), '100%'],
    ['Tonnage (MT)', '', '', sheet.grandTotal.tonnage.toFixed(3), ''],
  ]
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData)
  wsSummary['!cols'] = [{ wch: 14 }, { wch: 12 }, { wch: 18 }, { wch: 14 }, { wch: 12 }]
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary')

  // ── Sheet 2–5: Per member type ────────────────────────────────
  const types = ['beam', 'column', 'slab', 'foundation'] as const
  const typeLabels = { beam: 'Beams', column: 'Columns', slab: 'Slabs', foundation: 'Foundations' }

  for (const type of types) {
    const bars = sheet.bars.filter(b => b.memberType === type)
    if (bars.length === 0) continue

    const header = ['Mark', 'Member', 'Story', '⌀ (mm)', 'Shape', 'No. of Bars',
      'a (mm)', 'b (mm)', 'Cut Length (mm)', 'Weight/bar (kg)', 'Total Weight (kg)', 'Note']

    const rows = bars.map(b => [
      b.mark, b.memberLabel, b.storyLabel, b.dia, b.shape, b.noOfBars,
      b.a, b.b ?? '', b.totalLength,
      (b.totalWeight / b.noOfBars).toFixed(3),
      b.totalWeight.toFixed(2),
      b.note ?? '',
    ])

    const total = bars.reduce((s, b) => s + b.totalWeight, 0)
    rows.push(['', '', '', '', '', 'TOTAL', '', '', '', '', total.toFixed(2), ''])

    const ws = XLSX.utils.aoa_to_sheet([header, ...rows])
    ws['!cols'] = [
      { wch: 6 }, { wch: 12 }, { wch: 8 }, { wch: 8 }, { wch: 10 }, { wch: 10 },
      { wch: 8 }, { wch: 8 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 40 },
    ]
    XLSX.utils.book_append_sheet(wb, ws, typeLabels[type])
  }

  // ── Download ──────────────────────────────────────────────────
  const filename = `BBS-${sheet.projectName.replace(/\s+/g, '-')}-${sheet.date.replace(/\//g, '-')}.xlsx`
  XLSX.writeFile(wb, filename)
}

// ── DOCX Export (docx.js) ─────────────────────────────────────

export async function exportToDOCX(doc: ReportDocument): Promise<void> {
  const {
    Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
    HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  } = await import('docx')

  const children: any[] = []

  // Title page
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'CivilOS STRUCTURAL', bold: true, size: 40, color: 'EF4444' })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 2000 },
    }),
    new Paragraph({
      children: [new TextRun({ text: doc.title, bold: true, size: 28, color: '94A3B8' })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 200 },
    }),
    new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 400 } }),
  )

  // Project meta table
  const metaRows = [
    ['Project', doc.projectMeta.name],
    ['Project No.', doc.projectMeta.projectNo],
    ['Client', doc.projectMeta.client],
    ['Engineer', doc.projectMeta.engineer],
    ['Date', doc.projectMeta.date],
    ['Code', doc.projectMeta.code],
  ].map(([k, v]) => new TableRow({
    children: [
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: k, bold: true, size: 18, color: '64748B' })] })],
        shading: { type: ShadingType.CLEAR, fill: '0D1221' },
        width: { size: 30, type: WidthType.PERCENTAGE },
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: v || '—', size: 18 })] })],
        width: { size: 70, type: WidthType.PERCENTAGE },
      }),
    ],
  }))

  children.push(new Table({ rows: metaRows, width: { size: 100, type: WidthType.PERCENTAGE } }))
  children.push(new Paragraph({ children: [new TextRun({ text: '' })], pageBreakBefore: true }))

  // Sections
  for (const section of doc.sections) {
    if (section.id === 'cover') continue

    for (const item of section.content) {
      switch (item.type) {
        case 'heading':
          children.push(new Paragraph({
            children: [new TextRun({ text: item.text, bold: true,
              color: item.level === 1 ? 'EF4444' : item.level === 2 ? '3B82F6' : '94A3B8',
              size: item.level === 1 ? 24 : item.level === 2 ? 20 : 18,
            })],
            heading: item.level === 1 ? HeadingLevel.HEADING_1 : item.level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
            spacing: { before: 200, after: 100 },
          }))
          break

        case 'paragraph':
          children.push(new Paragraph({
            children: [new TextRun({ text: item.text, size: 18, color: '94A3B8' })],
            spacing: { before: 80, after: 80 },
          }))
          break

        case 'keyvalue':
          item.items.forEach(kv => {
            children.push(new Paragraph({
              children: [
                new TextRun({ text: kv.key + ': ', bold: true, size: 18, color: '64748B' }),
                new TextRun({ text: `${kv.value}${kv.unit ? ' ' + kv.unit : ''}`, size: 18 }),
              ],
              spacing: { before: 40 },
            }))
          })
          break

        case 'table':
          if (item.rows.length === 0) break
          children.push(new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              // Header
              new TableRow({
                children: item.headers.map(h => new TableCell({
                  children: [new Paragraph({ children: [new TextRun({ text: String(h), bold: true, size: 16, color: '3B82F6' })] })],
                  shading: { type: ShadingType.CLEAR, fill: '1E2D4A' },
                })),
              }),
              // Rows
              ...item.rows.map((row, ri) => new TableRow({
                children: row.map(cell => new TableCell({
                  children: [new Paragraph({ children: [new TextRun({ text: String(cell), size: 16 })] })],
                  shading: ri % 2 === 0
                    ? { type: ShadingType.CLEAR, fill: '0D1221' }
                    : undefined,
                })),
              })),
            ],
          }))
          children.push(new Paragraph({ children: [new TextRun({ text: '' })] }))
          break

        case 'checklist':
          item.items.forEach(ci => {
            const icons = { pass: '✓', fail: '✗', warning: '⚠', not_checked: '?' }
            const colors = { pass: '22C55E', fail: 'EF4444', warning: 'F97316', not_checked: '475569' }
            children.push(new Paragraph({
              children: [
                new TextRun({ text: `${icons[ci.status]} `, bold: true, color: colors[ci.status], size: 16 }),
                new TextRun({ text: ci.label, size: 16, color: '94A3B8' }),
                new TextRun({ text: `  ${ci.value}`, size: 16, color: '64748B' }),
              ],
              spacing: { before: 40 },
            }))
          })
          break

        case 'formula':
          children.push(new Paragraph({
            children: [
              new TextRun({ text: item.latex + '   ', bold: true, size: 18, color: '60A5FA' }),
              new TextRun({ text: item.description, size: 16, color: '64748B' }),
            ],
            spacing: { before: 100, after: 100 },
          }))
          break

        case 'spacer':
          children.push(new Paragraph({ children: [new TextRun({ text: '' })] }))
          break

        case 'pagebreak':
          children.push(new Paragraph({ children: [new TextRun({ text: '', break: 1 })], pageBreakBefore: true }))
          break
      }
    }
  }

  const docx = new Document({
    sections: [{ children }],
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 18, color: 'E2E8F0' },
        },
      },
    },
  })

  const blob = await Packer.toBlob(docx)
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `${doc.projectMeta.projectNo}-${doc.type}.docx`
  a.click()
  URL.revokeObjectURL(url)
}
